# docker-compose.yml
version: "3.8"

services:
  db:
    container_name: todo_db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d todo_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: todo_app
    build:
      context: .
      dockerfile: todo_backend/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      ROCKET_ADDRESS: "0.0.0.0"
      DATABASE_URL: "postgres://myuser:mypassword@db:5432/todo_db"
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8000/api/todos && exit 0 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  test_runner:
    container_name: webtodo_test_runner_1
    build:
      context: .
      dockerfile: todo_backend/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      ROCKET_ADDRESS: "0.0.0.0"
      DATABASE_URL: "postgres://myuser:mypassword@db:5432/todo_db"
    command: "cargo test"

volumes:
  postgres_data:
