# docker-compose.yml

version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: todo_postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d todo_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - todo_network

  app:
    build:
      context: .
      dockerfile: todo_backend/Dockerfile
    container_name: todo_rust_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      ROCKET_ADDRESS: "0.0.0.0"
      DATABASE_URL: "postgres://myuser:mypassword@db:5432/todo_db"
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8000/api/todos && exit 0 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - todo_network

  test_runner: # New service
    build:
      context: .
      dockerfile: todo_backend/Dockerfile
      target: builder
    image: todo_builder_img
    container_name: todo_test_runner
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://myuser:mypassword@db:5432/todo_db"
      RUST_LOG: debug
    working_dir: /usr/src/app/todo_backend
    volumes:
      - .:/usr/src/app
    command: sh -c "diesel migration run && cargo test -- --test-threads=1"
    networks:
      - todo_network

volumes:
  postgres_data:

networks:
  todo_network:
    driver: bridge
